-- Create tables for the dashboard data

-- GEO Scores
CREATE TABLE IF NOT EXISTS geo_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total NUMERIC,
    visibility NUMERIC,
    comprehension NUMERIC,
    representation NUMERIC,
    optimization NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Dimension Metrics
CREATE TABLE IF NOT EXISTS dimension_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_id TEXT NOT NULL, -- 'visibility', 'comprehension', etc.
    label TEXT,
    score NUMERIC,
    description TEXT,
    weight TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Sub Metrics for Dimensions
CREATE TABLE IF NOT EXISTS sub_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dimension_id TEXT REFERENCES dimension_metrics(dimension_id), -- This might need a better FK strategy if dimension_id is not unique, but assuming it is unique per report or we use a report_id. 
    -- For simplicity, let's just link by text id or parent id.
    -- Actually, let's make it simple.
    name TEXT,
    value TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Model Comparison
CREATE TABLE IF NOT EXISTS model_comparisons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region TEXT, -- 'china', 'global'
    model_name TEXT,
    score NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Recommendations
CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT,
    priority TEXT,
    title TEXT,
    suggestion TEXT,
    impact TEXT,
    action TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert some initial data (Mock data from frontend)
INSERT INTO geo_scores (total, visibility, comprehension, representation, optimization)
VALUES (82.4, 86, 79, 83, 77);

INSERT INTO model_comparisons (region, model_name, score) VALUES
('china', '文心一言', 90),
('china', '智谱GLM', 74),
('china', 'Kimi', 78),
('china', '豆包', 75),
('global', 'ChatGPT', 85),
('global', 'Claude', 83),
('global', 'Gemini', 81),
('global', 'Perplexity', 79);

INSERT INTO recommendations (type, priority, title, suggestion, impact, action) VALUES
('content', 'high', '结构化FAQ优化', '在官网首页添加FAQ结构化模块，明确品牌USP与关键词匹配', '+12% 理解度提升', '立即优化'),
('schema', 'medium', 'JSON-LD结构化数据', '为产品页增加JSON-LD标注以提高LLM索引能力', '+8% 可见度提升', '查看方案'),
('authority', 'high', '高权威信源扩展', '增加知乎专栏、CSDN等高权威平台的内容发布频率', '+15% 提及率提升', '制定策略');
